import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PNG } from 'pngjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const directory = resolve(root, 'src/experiments/ribbon-road')
// Tight object crops; text masks exclude only the lettering, never the sphere rim.
const figures = [
  { key: 'diffuseCloud', count: 3200, bounds: [30, 5, 590, 545], masks: [], scale: 1.08 },
  { key: 'noisySphere', count: 4000, bounds: [55, 75, 720, 710], masks: [[530, 60, 835, 108]], scale: 1.08 },
  { key: 'lens', count: 4000, bounds: [35, 35, 720, 680], masks: [[600, 82, 745, 129]], scale: 1.08 },
  { key: 'starBurst', count: 4500, bounds: [20, 8, 1170, 1148], masks: [], scale: 1.32 },
  { key: 'solidSphere', count: 4300, bounds: [345, 10, 1000, 625], masks: [[35, 65, 408, 115]], scale: 1.08 },
]
const stride = 8 // uint16 x/y; uint8 depth/alpha/size/brightness
const extent = 0.7
const clamp = (v, min = 0, max = 1) => Math.max(min, Math.min(max, v))
const byte = (v, min, max) => Math.round(clamp((v - min) / (max - min)) * 255)
const randomGenerator = (seed) => () => {
  seed |= 0
  seed = seed + 0x6D2B79F5 | 0
  let v = Math.imul(seed ^ seed >>> 15, 1 | seed)
  v = v + Math.imul(v ^ v >>> 7, 61 | v) ^ v
  return ((v ^ v >>> 14) >>> 0) / 4294967296
}

const generate = (figure, index) => {
  const png = PNG.sync.read(readFileSync(resolve(directory, 'assets', `figure${index + 1}.png`)))
  const [left, top, right, bottom] = figure.bounds
  const side = Math.max(right - left, bottom - top)
  const candidates = []
  let total = 0
  for (let y = top; y < bottom; y += 1) {
    for (let x = left; x < right; x += 1) {
      if (figure.masks.some(([l, t, r, b]) => x >= l && x <= r && y >= t && y <= b)) continue
      const offset = (y * png.width + x) * 4
      const luminance = (png.data[offset] * 0.2126 + png.data[offset + 1] * 0.7152
        + png.data[offset + 2] * 0.0722) / 255 * png.data[offset + 3] / 255
      // Remove the photographed black background, retain the faint interior and rays.
      const light = Math.max(0, (luminance - 0.035) / 0.965)
      if (light < 0.002) continue
      // Density carries the light distribution. Do NOT multiply it by luminance
      // again in alpha, size and glow: that erased the dark half of the spheres.
      total += Math.pow(light, 0.9)
      candidates.push({ x, y, cumulative: total })
    }
  }
  if (!total) throw new Error(`Empty reference: ${figure.key}`)
  const random = randomGenerator(731291 + index * 9109)
  const samples = []
  let cursor = 0
  for (let i = 0; i < figure.count; i += 1) {
    // Stratified CDF sampling covers faint contours instead of clustering randomly.
    const target = (i + random()) / figure.count * total
    while (candidates[cursor].cumulative < target) cursor += 1
    const { x, y } = candidates[cursor]
    samples.push([
      (x + random() - 0.5 - (left + right) / 2) / side * figure.scale,
      -(y + random() - 0.5 - (top + bottom) / 2) / side * figure.scale,
      (random() - 0.5) * 0.014,
      0.27 + random() * 0.055,
      0.83 + random() * 0.12,
      1.05,
    ])
  }
  // Shuffle before quality downsampling; each prefix retains the complete silhouette.
  for (let i = samples.length - 1; i > 0; i -= 1) {
    const j = Math.floor(random() * (i + 1))
    ;[samples[i], samples[j]] = [samples[j], samples[i]]
  }
  const data = Buffer.alloc(figure.count * stride)
  samples.forEach(([x, y, z, alpha, size, brightness], i) => {
    const offset = i * stride
    data.writeUInt16LE(Math.round(clamp((x + extent) / (2 * extent)) * 65535), offset)
    data.writeUInt16LE(Math.round(clamp((y + extent) / (2 * extent)) * 65535), offset + 2)
    data[offset + 4] = byte(z, -0.09, 0.09)
    data[offset + 5] = byte(alpha, 0.08, 0.82)
    data[offset + 6] = byte(size, 0.42, 1.75)
    data[offset + 7] = byte(brightness, 0.45, 1.45)
  })
  return `  ${figure.key}: { count: ${figure.count}, data: '${data.toString('base64')}' },`
}

const source = `// Generated by npm run generate:ribbon-figures. Do not edit by hand.
// uint16 LE x/y preserve subpixel positions; remaining channels are uint8.
export const PARTICLE_FIGURE_DATA = {
${figures.map(generate).join('\n')}
} as const
export const PARTICLE_FIGURE_ENCODING = {
  stride: 8,
  positionExtent: 0.7,
  depthExtent: 0.09,
  alphaRange: [0.08, 0.82],
  sizeRange: [0.42, 1.75],
  brightnessRange: [0.45, 1.45],
} as const
export type ParticleFigureKey = keyof typeof PARTICLE_FIGURE_DATA
`
writeFileSync(resolve(directory, 'particleFigureData.generated.ts'), source)
console.log(`Generated ${figures.reduce((sum, figure) => sum + figure.count, 0)} reference particles`)
